name: AutoCommit

on:
  schedule:
    - cron: '0 10 * * *'  # todos los días a las 10:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Modificar README
        run: |
          echo "- Última actualización: $(date -u)" >> README.md

      - name: Configurar Git
        run: |
          git config --global user.name "SsantiDev"
          git config --global user.email "ssantiago.xz1130@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit y push
        run: |
          git add README.md
          git commit -m "🕒 Commit automático: $(date -u)" || echo "Nada para commitear"
          git push origin HEAD:main
