name: AutoCommit

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Incrementar contador de días
        run: |
          COUNT=$(grep -oP '(?<=Días consecutivos de actividad: )\d+' README.md || echo 0)
          NEW_COUNT=$((COUNT + 1))
          sed -i "s/Días consecutivos de actividad: $COUNT/Días consecutivos de actividad: $NEW_COUNT/" README.md

      - name: Configurar Git para autenticación con token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper 'store'
          echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Commit y push
        run: |
          git add README.md
          git commit -m "🕒 Commit automático: $(date -u)" || echo "Nada para commitear"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
